services:
  redis_host:
    image: redis:latest
    container_name: redis_host
    restart: always
    ports:
      - 7234:6379
    command: ["redis-server", "--appendonly", "yes"]
    networks:
      - rds-tsk

  dispatcher_service_1:
    container_name: dispatcher_service_1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=dispatcher
    restart: always
    environment:
      - REDIS_PUBLISHER_URL=redis://redis_host:6379
      - LEADERSHIP_TTL_IN_SECONDS=${LEADERSHIP_TTL_IN_SECONDS}
      - CONSUMER_URLS=consumer_service_1:6969,consumer_service_2:7001,consumer_service_3:7002
      - ACKNOWLEDGER_PORT=5001
      - PROMETHEUS_PUSHGATEWAY_URL=http://pushgateway:9091
    ports:
      - 5001:5001
    depends_on:
      - redis_host
    networks:
      - rds-tsk

  dispatcher_service_2:
    container_name: dispatcher_service_2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=dispatcher
    restart: always
    environment:
      - REDIS_PUBLISHER_URL=redis://redis_host:6379
      - LEADERSHIP_TTL_IN_SECONDS=${LEADERSHIP_TTL_IN_SECONDS}
      - CONSUMER_URLS=consumer_service_1:6969,consumer_service_2:7001,consumer_service_3:7002
      - ACKNOWLEDGER_PORT=5002
      - PROMETHEUS_PUSHGATEWAY_URL=http://pushgateway:9091
    ports:
      - 5002:5002
    depends_on:
      - redis_host
    networks:
      - rds-tsk

  consumer_service_1:
    container_name: consumer_service_1
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=consumer
    restart: always
    environment:
      - CONSUMER_PORT=6969
      - REDIS_PUBLISHER_URL=redis://redis_host:6379
      - ACK_HOSTS=dispatcher_service_1:5001,dispatcher_service_2:5002
    ports:
      - 6969:6969
    depends_on:
      - redis_host
    networks:
      - rds-tsk

  consumer_service_2:
    container_name: consumer_service_2
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=consumer
    restart: always
    environment:
      - CONSUMER_PORT=7001
      - REDIS_PUBLISHER_URL=redis://redis_host:6379
      - ACK_HOSTS=dispatcher_service_1:5001,dispatcher_service_2:5002
    ports:
      - 7001:7001
    depends_on:
      - redis_host
    networks:
      - rds-tsk

  consumer_service_3:
    container_name: consumer_service_3
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - WORKSPACE=consumer
    restart: always
    environment:
      - CONSUMER_PORT=7002
      - REDIS_PUBLISHER_URL=redis://redis_host:6379
      - ACK_HOSTS=dispatcher_service_1:5001,dispatcher_service_2:5002
    ports:
      - 7002:7002
    depends_on:
      - redis_host
    networks:
      - rds-tsk
  pumba:
    image: gaiaadm/pumba:latest
    container_name: pumba
    entrypoint: ["/pumba"]
    command:
      - --log-level
      - info 
      - --interval
      - 15s
      - --random
      - stop 
      - --duration
      - 1s
      - --restart
      - re2:^(consumer|dispatcher).*
    networks:
      - rds-tsk
    tty: true
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock" 

  loki:
    image: grafana/loki:2.8.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      - rds-tsk

  promtail:
    image: grafana/promtail:2.8.2
    container_name: promtail
    volumes:
      - /var/log:/var/log
      - ./promtail-config.yaml:/etc/promtail/config.yaml
      - "/var/run/docker.sock:/var/run/docker.sock"
    command: -config.file=/etc/promtail/config.yaml
    networks:
      - rds-tsk
    depends_on:
      - loki

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
      - GF_AUTH_ANONYMOUS_ENABLED=true
    volumes:
      - grafana-storage:/var/lib/grafana
    networks:
      - rds-tsk
    depends_on:
      - loki

  pushgateway:
    image: prom/pushgateway:latest
    container_name: pushgateway
    restart: always
    ports:
      - "9091:9091"
    networks:
      - rds-tsk

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: always
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus-config.yaml:/etc/prometheus/prometheus.yml
    networks:
      - rds-tsk
    depends_on:
      - pushgateway
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

networks:
  rds-tsk:
    driver: bridge

volumes:
  grafana-storage:

